server:
  port: 8080
spring:
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://localhost:3309/ssm?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


mybatis:
  typeAliasesPackage: com.ssm.entity
  mapperLocations:  classpath:mapper/*Mapper.xml